export const shopCategories = [
  { value: "fashion", label: "Fashion" },
  { value: "electronics", label: "Electronics" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "home-decor", label: "Home & Decor" },
  { value: "fitness", label: "Fitness & Sports" },
  { value: "food", label: "Food & Beverages" },
  { value: "handmade", label: "Handmade & Crafts" },
  { value: "books", label: "Books & Stationery" },
  { value: "toys", label: "Toys & Games" },
  { value: "automotive", label: "Automotive" },
  { value: "pets", label: "Pet Supplies" },
  { value: "gadgets", label: "Gadgets & Accessories" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "services", label: "Services" },
  { value: "digital", label: "Digital Products" },
];

export const businessCategories = [
  { label: "Financial Services", value: "financial_services" },
  { label: "Education", value: "education" },
  { label: "Healthcare", value: "healthcare" },
  { label: "Utilities", value: "utilities" },
  { label: "Government", value: "government" },
  { label: "Logistics", value: "logistics" },
  { label: "Tours and Travel", value: "tours_and_travel" },
  { label: "Transport", value: "transport" },
  { label: "E-commerce", value: "ecommerce" },
  { label: "Food", value: "food" },
  { label: "IT and Software", value: "it_and_software" },
  { label: "Gaming", value: "gaming" },
  { label: "Media and Entertainment", value: "media_and_entertainment" },
  { label: "Services", value: "services" },
  { label: "Housing", value: "housing" },
  { label: "Not for Profit", value: "not_for_profit" },
  { label: "Social", value: "social" },
  { label: "Others", value: "others" },
];

export const businessSubCategories = {
  FINANCIAL_SERVICES: [
    { label: "mutual_fund", value: "mutual_fund" },
    { label: "lending", value: "lending" },
    { label: "cryptocurrency", value: "cryptocurrency" },
    { label: "insurance", value: "insurance" },
    { label: "nbfc", value: "nbfc" },
    { label: "cooperatives", value: "cooperatives" },
    { label: "pension_fund", value: "pension_fund" },
    { label: "forex", value: "forex" },
    { label: "securities", value: "securities" },
    { label: "commodities", value: "commodities" },
    { label: "accounting", value: "accounting" },
    { label: "financial_advisor", value: "financial_advisor" },
    { label: "crowdfunding", value: "crowdfunding" },
    { label: "trading", value: "trading" },
    { label: "betting", value: "betting" },
    { label: "get_rich_schemes", value: "get_rich_schemes" },
    { label: "moneysend_funding", value: "moneysend_funding" },
    {
      label: "wire_transfers_and_money_orders",
      value: "wire_transfers_and_money_orders",
    },
    { label: "tax_preparation_services", value: "tax_preparation_services" },
    { label: "tax_payments", value: "tax_payments" },
    { label: "digital_goods", value: "digital_goods" },
    { label: "atms", value: "atms" },
  ],
  EDUCATION: [
    { label: "college", value: "college" },
    { label: "schools", value: "schools" },
    { label: "university", value: "university" },
    { label: "professional_courses", value: "professional_courses" },
    { label: "distance_learning", value: "distance_learning" },
    { label: "day_care", value: "day_care" },
    { label: "coaching", value: "coaching" },
    { label: "elearning", value: "elearning" },
    {
      label: "vocational_and_trade_schools",
      value: "vocational_and_trade_schools",
    },
    { label: "sporting_clubs", value: "sporting_clubs" },
    {
      label: "dance_halls_studios_and_schools",
      value: "dance_halls_studios_and_schools",
    },
    { label: "correspondence_schools", value: "correspondence_schools" },
  ],
  HEALTHCARE: [
    { label: "pharmacy", value: "pharmacy" },
    { label: "clinic", value: "clinic" },
    { label: "hospital", value: "hospital" },
    { label: "lab", value: "lab" },
    { label: "dietician", value: "dietician" },
    { label: "fitness", value: "fitness" },
    { label: "health_coaching", value: "health_coaching" },
    { label: "health_products", value: "health_products" },
    { label: "drug_stores", value: "drug_stores" },
    { label: "healthcare_marketplace", value: "healthcare_marketplace" },
    { label: "osteopaths", value: "osteopaths" },
    {
      label: "medical_equipment_and_supply_stores",
      value: "medical_equipment_and_supply_stores",
    },
    {
      label: "podiatrists_and_chiropodists",
      value: "podiatrists_and_chiropodists",
    },
    {
      label: "dentists_and_orthodontists",
      value: "dentists_and_orthodontists",
    },
    { label: "hardware_stores", value: "hardware_stores" },
    { label: "ophthalmologists", value: "ophthalmologists" },
    { label: "orthopedic_goods_stores", value: "orthopedic_goods_stores" },
    { label: "testing_laboratories", value: "testing_laboratories" },
    { label: "doctors", value: "doctors" },
    {
      label: "health_practitioners_medical_services",
      value: "health_practitioners_medical_services",
    },
    { label: "testing_laboratories", value: "testing_laboratories" },
  ],
  ECOMMERCE: [
    { label: "ecommerce_marketplace", value: "ecommerce_marketplace" },
    { label: "agriculture", value: "agriculture" },
    { label: "books", value: "books" },
    { label: "electronics_and_furniture", value: "electronics_and_furniture" },
    { label: "coupons", value: "coupons" },
    { label: "rental", value: "rental" },
    { label: "fashion_and_lifestyle", value: "fashion_and_lifestyle" },
    { label: "gifting", value: "gifting" },
    { label: "grocery", value: "grocery" },
    { label: "baby_products", value: "baby_products" },
    { label: "office_supplies", value: "office_supplies" },
    { label: "wholesale", value: "wholesale" },
    { label: "religious_products", value: "religious_products" },
    { label: "pet_products", value: "pet_products" },
    { label: "sports_products", value: "sports_products" },
    { label: "arts_and_collectibles", value: "arts_and_collectibles" },
    { label: "sexual_wellness_products", value: "sexual_wellness_products" },
    { label: "drop_shipping", value: "drop_shipping" },
    { label: "crypto_machinery", value: "crypto_machinery" },
    { label: "tobacco", value: "tobacco" },
    { label: "weapons_and_ammunitions", value: "weapons_and_ammunitions" },
    { label: "stamps_and_coins_stores", value: "stamps_and_coins_stores" },
    { label: "office_equipment", value: "office_equipment" },
    {
      label: "automobile_parts_and_equipements",
      value: "automobile_parts_and_equipements",
    },
    { label: "garden_supply_stores", value: "garden_supply_stores" },
    {
      label: "household_appliance_stores",
      value: "household_appliance_stores",
    },
    { label: "non_durable_goods", value: "non_durable_goods" },
    { label: "pawn_shops", value: "pawn_shops" },
    {
      label: "electrical_parts_and_equipment",
      value: "electrical_parts_and_equipment",
    },
    { label: "wig_and_toupee_shops", value: "wig_and_toupee_shops" },
    {
      label: "gift_novelty_and_souvenir_shops",
      value: "gift_novelty_and_souvenir_shops",
    },
    { label: "duty_free_stores", value: "duty_free_stores" },
    {
      label: "office_and_commercial_furniture",
      value: "office_and_commercial_furniture",
    },
    { label: "dry_goods", value: "dry_goods" },
    { label: "books_and_publications", value: "books_and_publications" },
    {
      label: "camera_and_photographic_stores",
      value: "camera_and_photographic_stores",
    },
    { label: "record_shops", value: "record_shops" },
    { label: "meat_supply_stores", value: "meat_supply_stores" },
    { label: "leather_goods_and_luggage", value: "leather_goods_and_luggage" },
    { label: "snowmobile_dealers", value: "snowmobile_dealers" },
    {
      label: "men_and_boys_clothing_stores",
      value: "men_and_boys_clothing_stores",
    },
    { label: "paint_supply_stores", value: "paint_supply_stores" },
    { label: "automotive_parts", value: "automotive_parts" },
    {
      label: "jewellery_and_watch_stores",
      value: "jewellery_and_watch_stores",
    },
    {
      label: "auto_store_home_supply_stores",
      value: "auto_store_home_supply_stores",
    },
    { label: "tent_stores", value: "tent_stores" },
    { label: "shoe_stores_retail", value: "shoe_stores_retail" },
    {
      label: "petroleum_and_petroleum_products",
      value: "petroleum_and_petroleum_products",
    },
    { label: "department_stores", value: "department_stores" },
    { label: "automotive_tire_stores", value: "automotive_tire_stores" },
    { label: "sport_apparel_stores", value: "sport_apparel_stores" },
    { label: "variety_stores", value: "variety_stores" },
    {
      label: "chemicals_and_allied_products",
      value: "chemicals_and_allied_products",
    },
    { label: "commercial_equipments", value: "commercial_equipments" },
    {
      label: "fireplace_parts_and_accessories",
      value: "fireplace_parts_and_accessories",
    },
    { label: "family_clothing_stores", value: "family_clothing_stores" },
    { label: "fabric_and_sewing_stores", value: "fabric_and_sewing_stores" },
    { label: "home_supply_warehouse", value: "home_supply_warehouse" },
    { label: "art_supply_stores", value: "art_supply_stores" },
    {
      label: "camper_recreational_and_utility_trailer_dealers",
      value: "camper_recreational_and_utility_trailer_dealers",
    },
    {
      label: "clocks_and_silverware_stores",
      value: "clocks_and_silverware_stores",
    },
    { label: "discount_stores", value: "discount_stores" },
    {
      label: "school_supplies_and_stationery",
      value: "school_supplies_and_stationery",
    },
    { label: "second_hand_stores", value: "second_hand_stores" },
    {
      label: "watch_and_jewellery_repair_stores",
      value: "watch_and_jewellery_repair_stores",
    },
    { label: "liquor_stores", value: "liquor_stores" },
    { label: "boat_dealers", value: "boat_dealers" },
    {
      label: "opticians_optical_goods_and_eyeglasse_stores",
      value: "opticians_optical_goods_and_eyeglasse_stores",
    },
    { label: "wholesale_footwear_stores", value: "wholesale_footwear_stores" },
    { label: "cosmetic_stores", value: "cosmetic_stores" },
    { label: "home_furnishing_stores", value: "home_furnishing_stores" },
    { label: "antique_stores", value: "antique_stores" },
    {
      label: "plumbing_and_heating_equipment",
      value: "plumbing_and_heating_equipment",
    },
    {
      label: "telecommunication_equipment_stores",
      value: "telecommunication_equipment_stores",
    },
    { label: "women_clothing", value: "women_clothing" },
    { label: "florists", value: "florists" },
    { label: "computer_software_stores", value: "computer_software_stores" },
    { label: "building_matrial_stores", value: "building_matrial_stores" },
    {
      label: "candy_nut_confectionery_shops",
      value: "candy_nut_confectionery_shops",
    },
    {
      label: "glass_and_wallpaper_stores",
      value: "glass_and_wallpaper_stores",
    },
    {
      label: "commercial_photography_and_graphic_design_services",
      value: "commercial_photography_and_graphic_design_services",
    },
    { label: "video_game_supply_stores", value: "video_game_supply_stores" },
    { label: "fuel_dealers", value: "fuel_dealers" },
    {
      label: "drapery_and_window_coverings_stores",
      value: "drapery_and_window_coverings_stores",
    },
    { label: "hearing_aids_stores", value: "hearing_aids_stores" },
    { label: "automotive_paint_shops", value: "automotive_paint_shops" },
    { label: "durable_goods_stores", value: "durable_goods_stores" },
    {
      label: "uniforms_and_commercial_clothing_stores",
      value: "uniforms_and_commercial_clothing_stores",
    },
    { label: "fur_shops", value: "fur_shops" },
    { label: "industrial_supplies", value: "industrial_supplies" },
    { label: "bicycle_stores", value: "bicycle_stores" },
    { label: "second_hand_stores", value: "second_hand_stores" },
    {
      label: "motorcycle_shops_and_dealers",
      value: "motorcycle_shops_and_dealers",
    },
    {
      label: "children_and_infants_wear_stores",
      value: "children_and_infants_wear_stores",
    },
    { label: "women_accessory_stores", value: "women_accessory_stores" },
    { label: "construction_materials", value: "construction_materials" },
    {
      label: "books_periodicals_and_newspaper",
      value: "books_periodicals_and_newspaper",
    },
    { label: "floor_covering_stores", value: "floor_covering_stores" },
    {
      label: "crystal_and_glassware_stores",
      value: "crystal_and_glassware_stores",
    },
    {
      label: "accessory_and_apparel_stores",
      value: "accessory_and_apparel_stores",
    },
    {
      label: "hardware_equipment_and_supply_stores",
      value: "hardware_equipment_and_supply_stores",
    },
    {
      label: "computers_peripheral_equipment_software",
      value: "computers_peripheral_equipment_software",
    },
    {
      label: "automobile_and_truck_dealers",
      value: "automobile_and_truck_dealers",
    },
    {
      label: "aircraft_and_farm_equipment_dealers",
      value: "aircraft_and_farm_equipment_dealers",
    },
    {
      label: "antique_shops_sales_and_repairs",
      value: "antique_shops_sales_and_repairs",
    },
    { label: "hearing_aids_stores", value: "hearing_aids_stores" },
    { label: "music_stores", value: "music_stores" },
    {
      label: "furniture_and_home_furnishing_store",
      value: "furniture_and_home_furnishing_store",
    },
  ],
  SERVICES: [
    { label: "repair_and_cleaning", value: "repair_and_cleaning" },
    {
      label: "interior_design_and_architect",
      value: "interior_design_and_architect",
    },
    { label: "movers_and_packers", value: "movers_and_packers" },
    { label: "legal", value: "legal" },
    { label: "event_planning", value: "event_planning" },
    { label: "service_centre", value: "service_centre" },
    { label: "consulting", value: "consulting" },
    { label: "ad_and_marketing", value: "ad_and_marketing" },
    { label: "services_classifieds", value: "services_classifieds" },
    { label: "multi_level_marketing", value: "multi_level_marketing" },
    { label: "construction_services", value: "construction_services" },
    { label: "architectural_services", value: "architectural_services" },
    { label: "car_washes", value: "car_washes" },
    { label: "motor_home_rentals", value: "motor_home_rentals" },
    {
      label: "stenographic_and_secretarial_support_services",
      value: "stenographic_and_secretarial_support_services",
    },
    { label: "chiropractors", value: "chiropractors" },
    { label: "automotive_service_shops", value: "automotive_service_shops" },
    { label: "shoe_repair_shops", value: "shoe_repair_shops" },
    { label: "telecommunication_service", value: "telecommunication_service" },
    { label: "fines", value: "fines" },
    { label: "security_agencies", value: "security_agencies" },
    { label: "tailors", value: "tailors" },
    {
      label: "type_setting_and_engraving_services",
      value: "type_setting_and_engraving_services",
    },
    {
      label: "small_appliance_repair_shops",
      value: "small_appliance_repair_shops",
    },
    { label: "photography_labs", value: "photography_labs" },
    { label: "dry_cleaners", value: "dry_cleaners" },
    { label: "massage_parlors", value: "massage_parlors" },
    { label: "electronic_repair_shops", value: "electronic_repair_shops" },
    {
      label: "cleaning_and_sanitation_services",
      value: "cleaning_and_sanitation_services",
    },
    { label: "nursing_care_facilities", value: "nursing_care_facilities" },
    { label: "direct_marketing", value: "direct_marketing" },
    { label: "lottery", value: "lottery" },
    { label: "veterinary_services", value: "veterinary_services" },
    { label: "affliated_auto_rental", value: "affliated_auto_rental" },
    { label: "alimony_and_child_support", value: "alimony_and_child_support" },
    { label: "airport_flying_fields", value: "airport_flying_fields" },
    { label: "golf_courses", value: "golf_courses" },
    {
      label: "tire_retreading_and_repair_shops",
      value: "tire_retreading_and_repair_shops",
    },
    { label: "television_cable_services", value: "television_cable_services" },
    {
      label: "recreational_and_sporting_camps",
      value: "recreational_and_sporting_camps",
    },
    { label: "barber_and_beauty_shops", value: "barber_and_beauty_shops" },
    { label: "agricultural_cooperatives", value: "agricultural_cooperatives" },
    { label: "carpentry_contractors", value: "carpentry_contractors" },
    {
      label: "wrecking_and_salvaging_services",
      value: "wrecking_and_salvaging_services",
    },
    {
      label: "automobile_towing_services",
      value: "automobile_towing_services",
    },
    { label: "video_tape_rental_stores", value: "video_tape_rental_stores" },
    {
      label: "miscellaneous_repair_shops",
      value: "miscellaneous_repair_shops",
    },
    { label: "motor_homes_and_parts", value: "motor_homes_and_parts" },
    { label: "horse_or_dog_racing", value: "horse_or_dog_racing" },
    { label: "laundry_services", value: "laundry_services" },
    { label: "electrical_contractors", value: "electrical_contractors" },
    {
      label: "debt_marriage_personal_counseling_service",
      value: "debt_marriage_personal_counseling_service",
    },
    {
      label: "air_conditioning_and_refrigeration_repair_shops",
      value: "air_conditioning_and_refrigeration_repair_shops",
    },
    { label: "credit_reporting_agencies", value: "credit_reporting_agencies" },
    {
      label: "heating_and_plumbing_contractors",
      value: "heating_and_plumbing_contractors",
    },
    {
      label: "carpet_and_upholstery_cleaning_services",
      value: "carpet_and_upholstery_cleaning_services",
    },
    { label: "swimming_pools", value: "swimming_pools" },
    {
      label: "roofing_and_metal_work_contractors",
      value: "roofing_and_metal_work_contractors",
    },
    {
      label: "internet_service_providers",
      value: "internet_service_providers",
    },
    { label: "recreational_camps", value: "recreational_camps" },
    { label: "masonry_contractors", value: "masonry_contractors" },
    {
      label: "exterminating_and_disinfecting_services",
      value: "exterminating_and_disinfecting_services",
    },
    { label: "ambulance_services", value: "ambulance_services" },
    {
      label: "funeral_services_and_crematories",
      value: "funeral_services_and_crematories",
    },
    { label: "metal_service_centres", value: "metal_service_centres" },
    {
      label: "copying_and_blueprinting_services",
      value: "copying_and_blueprinting_services",
    },
    { label: "fuel_dispensers", value: "fuel_dispensers" },
    { label: "welding_repair", value: "welding_repair" },
    { label: "mobile_home_dealers", value: "mobile_home_dealers" },
    { label: "concrete_work_contractors", value: "concrete_work_contractors" },
    { label: "boat_rentals", value: "boat_rentals" },
    {
      label: "personal_shoppers_and_shopping_clubs",
      value: "personal_shoppers_and_shopping_clubs",
    },
    { label: "door_to_door_sales", value: "door_to_door_sales" },
    {
      label: "travel_related_direct_marketing",
      value: "travel_related_direct_marketing",
    },
    { label: "lottery_and_betting", value: "lottery_and_betting" },
    {
      label: "bands_orchestras_and_miscellaneous_entertainers",
      value: "bands_orchestras_and_miscellaneous_entertainers",
    },
    {
      label: "furniture_repair_and_refinishing",
      value: "furniture_repair_and_refinishing",
    },
    { label: "contractors", value: "contractors" },
    {
      label: "direct_marketing_and_subscription_merchants",
      value: "direct_marketing_and_subscription_merchants",
    },
    {
      label: "typewriter_stores_sales_service_and_rentals",
      value: "typewriter_stores_sales_service_and_rentals",
    },
    { label: "recreation_services", value: "recreation_services" },
    {
      label: "direct_marketing_insurance_services",
      value: "direct_marketing_insurance_services",
    },
    { label: "business_services", value: "business_services" },
    {
      label: "inbound_telemarketing_merchants",
      value: "inbound_telemarketing_merchants",
    },
    { label: "public_warehousing", value: "public_warehousing" },
    {
      label: "outbound_telemarketing_merchants",
      value: "outbound_telemarketing_merchants",
    },
    { label: "clothing_rental_stores", value: "clothing_rental_stores" },
    { label: "transportation_services", value: "transportation_services" },
    { label: "electric_razor_stores", value: "electric_razor_stores" },
    { label: "service_stations", value: "service_stations" },
    { label: "photographic_studio", value: "photographic_studio" },
    { label: "professional_services", value: "professional_services" },
  ],
  HOUSING: [
    { label: "developer", value: "developer" },
    { label: "facility_management", value: "facility_management" },
    { label: "rwa", value: "rwa" },
    { label: "coworking", value: "coworking" },
    { label: "realestate_classifieds", value: "realestate_classifieds" },
    { label: "space_rental", value: "space_rental" },
  ],
  NOT_FOR_PROFIT: [
    { label: "charity", value: "charity" },
    { label: "educational", value: "educational" },
    { label: "religious", value: "religious" },
    { label: "personal", value: "personal" },
  ],
  SOCIAL: [
    { label: "matchmaking", value: "matchmaking" },
    { label: "social_network", value: "social_network" },
    { label: "messaging", value: "messaging" },
    { label: "professional_network", value: "professional_network" },
    { label: "neighbourhood_network", value: "neighbourhood_network" },
    { label: "political_organizations", value: "political_organizations" },
    {
      label: "automobile_associations_and_clubs",
      value: "automobile_associations_and_clubs",
    },
    {
      label: "country_and_athletic_clubs",
      value: "country_and_athletic_clubs",
    },
    {
      label: "associations_and_membership",
      value: "associations_and_membership",
    },
  ],
  MEDIA_AND_ENTERTAINMENT: [
    { label: "video_on_demand", value: "video_on_demand" },
    { label: "music_streaming", value: "music_streaming" },
    { label: "multiplex", value: "multiplex" },
    { label: "content_and_publishing", value: "content_and_publishing" },
    { label: "ticketing", value: "ticketing" },
    { label: "news", value: "news" },
    { label: "video_game_arcades", value: "video_game_arcades" },
    {
      label: "video_tape_production_and_distribution",
      value: "video_tape_production_and_distribution",
    },
    { label: "bowling_alleys", value: "bowling_alleys" },
    {
      label: "billiard_and_pool_establishments",
      value: "billiard_and_pool_establishments",
    },
    {
      label: "amusement_parks_and_circuses",
      value: "amusement_parks_and_circuses",
    },
    { label: "ticket_agencies", value: "ticket_agencies" },
  ],
  GAMING: [
    { label: "game_developer", value: "game_developer" },
    { label: "esports", value: "esports" },
    { label: "online_casino", value: "online_casino" },
    { label: "fantasy_sports", value: "fantasy_sports" },
    { label: "gaming_marketplace", value: "gaming_marketplace" },
  ],
  IT_AND_SOFTWARE: [
    { label: "saas", value: "saas" },
    { label: "paas", value: "paas" },
    { label: "iaas", value: "iaas" },
    {
      label: "consulting_and_outsourcing",
      value: "consulting_and_outsourcing",
    },
    { label: "web_development", value: "web_development" },
    { label: "technical_support", value: "technical_support" },
    { label: "data_processing", value: "data_processing" },
  ],
  FOOD: [
    { label: "online_food_ordering", value: "online_food_ordering" },
    { label: "restaurant", value: "restaurant" },
    { label: "food_court", value: "food_court" },
    { label: "catering", value: "catering" },
    { label: "alcohol", value: "alcohol" },
    {
      label: "restaurant_search_and_booking",
      value: "restaurant_search_and_booking",
    },
    { label: "dairy_products", value: "dairy_products" },
    { label: "bakeries", value: "bakeries" },
  ],
  UTILITIES: [
    { label: "electricity", value: "electricity" },
    { label: "gas", value: "gas" },
    { label: "telecom", value: "telecom" },
    { label: "water", value: "water" },
    { label: "cable", value: "cable" },
    { label: "broadband", value: "broadband" },
    { label: "dth", value: "dth" },
    { label: "internet_provider", value: "internet_provider" },
    {
      label: "bill_and_recharge_aggregators",
      value: "bill_and_recharge_aggregators",
    },
  ],
  GOVERNMENT: [
    { label: "central", value: "central" },
    { label: "state", value: "state" },
    {
      label: "intra_government_purchases",
      value: "intra_government_purchases",
    },
    { label: "goverment_postal_services", value: "goverment_postal_services" },
  ],
  LOGISTICS: [
    { label: "freight", value: "freight" },
    { label: "courier", value: "courier" },
    { label: "warehousing", value: "warehousing" },
    { label: "distribution", value: "distribution" },
    { label: "end_to_end_logistics", value: "end_to_end_logistics" },
    { label: "courier_services", value: "courier_services" },
  ],
  TOURS_AND_TRAVEL: [
    { label: "aviation", value: "aviation" },
    { label: "accommodation", value: "accommodation" },
    { label: "ota", value: "ota" },
    { label: "travel_agency", value: "travel_agency" },
    {
      label: "tourist_attractions_and_exhibits",
      value: "tourist_attractions_and_exhibits",
    },
    { label: "timeshares", value: "timeshares" },
    {
      label: "aquariums_dolphinariums_and_seaquariums",
      value: "aquariums_dolphinariums_and_seaquariums",
    },
  ],
  TRANSPORT: [
    { label: "cab_hailing", value: "cab_hailing" },
    { label: "bus", value: "bus" },
    { label: "train_and_metro", value: "train_and_metro" },
    { label: "automobile_rentals", value: "automobile_rentals" },
    { label: "cruise_lines", value: "cruise_lines" },
    { label: "parking_lots_and_garages", value: "parking_lots_and_garages" },
    { label: "transportation", value: "transportation" },
    { label: "bridge_and_road_tolls", value: "bridge_and_road_tolls" },
    { label: "freight_transport", value: "freight_transport" },
    {
      label: "truck_and_utility_trailer_rentals",
      value: "truck_and_utility_trailer_rentals",
    },
  ],
};

export const businessType = [
  { label: "LLP", value: "LLP" },
  { label: "NGO", value: "NGO" },
  { label: "Individual", value: "Individual" },
  { label: "Partnership", value: "Partnership" },
  { label: "Proprietorship", value: "Proprietorship" },
  { label: "Public Limited", value: "Public Limited" },
  { label: "Private Limited", value: "Private Limited" },
  { label: "Trust", value: "Trust" },
  { label: "Society", value: "Society" },
  { label: "Hindu Undivided Family", value: "Hindu Undivided Family" },
  { label: "Association of Persons", value: "Association of Persons" },
  { label: "Body of Individuals", value: "Body of Individuals" },
  { label: "Local Authority", value: "Local Authority" },
  {
    label: "Artificial Juridical Person",
    value: "Artificial Juridical Person",
  },
  { label: "Government", value: "Government" },
  { label: "Other", value: "other" },
];
